export const modulosComerciais = [
  { id: "core", nome: "Núcleo NEXUS", categoria: "Base", valorMensal: 390, obrigatorio: true },
  { id: "educacao", nome: "NEXUS Educação", categoria: "Portfólio", valorMensal: 690 },
  { id: "saude", nome: "NEXUS Saúde", categoria: "Portfólio", valorMensal: 890 },
  { id: "restaurantes", nome: "NEXUS Restaurantes", categoria: "Portfólio", valorMensal: 490 },
  { id: "governamental", nome: "NEXUS Governamental", categoria: "Portfólio", valorMensal: 1190 },
  { id: "familia", nome: "Portal da Família", categoria: "Complementar", valorMensal: 190 },
  { id: "ia", nome: "Assistente NEXUS IA", categoria: "Complementar", valorMensal: 350 },
  { id: "bi", nome: "Painel Executivo e BI", categoria: "Complementar", valorMensal: 290 },
  { id: "hospedagem", nome: "Hospedagem Gerenciada", categoria: "Infraestrutura", valorMensal: 220 },
  { id: "suporte", nome: "Suporte Prioritário", categoria: "Serviço", valorMensal: 280 },
];

export const planosComerciais = [
  {
    id: "essencial",
    nome: "Essencial",
    descricao: "Operação inicial para uma unidade.",
    valorBase: 790,
    limiteUnidades: 1,
    modulos: ["core", "hospedagem"],
  },
  {
    id: "profissional",
    nome: "Profissional",
    descricao: "Gestão multiunidade com indicadores e suporte.",
    valorBase: 1490,
    limiteUnidades: 5,
    modulos: ["core", "bi", "hospedagem", "suporte"],
  },
  {
    id: "enterprise",
    nome: "Enterprise",
    descricao: "Operação corporativa, integrações e expansão sob demanda.",
    valorBase: 2990,
    limiteUnidades: null,
    modulos: ["core", "bi", "ia", "hospedagem", "suporte"],
  },
];

export const clientesIniciais = [
  {
    id: "CLI-001",
    nome: "Colégio Horizonte",
    documento: "12.345.678/0001-90",
    contato: "Mariana Souza",
    email: "gestao@colegiohorizonte.com.br",
    segmento: "Educação",
    unidades: 4,
    plano: "Profissional",
    modulos: ["NEXUS Educação", "Portal da Família", "Hospedagem Gerenciada"],
    inicioContrato: "01/08/2026",
    fimContrato: "31/07/2027",
    vencimento: "10 de cada mês",
    valorMensal: 2590,
    status: "Ativo",
  },
  {
    id: "CLI-002",
    nome: "Rede Clínica Viver",
    documento: "98.765.432/0001-21",
    contato: "Renato Lima",
    email: "diretoria@clinicaviver.com.br",
    segmento: "Saúde",
    unidades: 2,
    plano: "Enterprise",
    modulos: ["NEXUS Saúde", "Assistente NEXUS IA", "Hospedagem Gerenciada"],
    inicioContrato: "15/07/2026",
    fimContrato: "14/07/2027",
    vencimento: "15 de cada mês",
    valorMensal: 4450,
    status: "Ativo",
  },
  {
    id: "CLI-003",
    nome: "Bistrô Central",
    documento: "45.112.900/0001-07",
    contato: "Paulo Andrade",
    email: "financeiro@bistrocentral.com.br",
    segmento: "Restaurantes",
    unidades: 1,
    plano: "Essencial",
    modulos: ["NEXUS Restaurantes", "Hospedagem Gerenciada"],
    inicioContrato: "20/08/2026",
    fimContrato: "19/08/2027",
    vencimento: "20 de cada mês",
    valorMensal: 1280,
    status: "Implantação",
  },
];
