export const FACILITIES_PLENIUM = Object.freeze({
  portal: { id: "portal", nome: "PLENIUM Portal", custoVariavel: false },
  whatsapp: { id: "whatsapp", nome: "PLENIUM WhatsApp", custoVariavel: true, unidadeCusto: "mensagem/conversa" },
  site: { id: "site", nome: "PLENIUM Site", custoVariavel: false },
  reservas: { id: "reservas", nome: "PLENIUM Reservas", custoVariavel: false },
  agendaOnline: { id: "agenda-online", nome: "PLENIUM Agenda Online", custoVariavel: false },
  delivery: { id: "delivery", nome: "PLENIUM Delivery", custoVariavel: false },
  cobrancas: { id: "cobrancas", nome: "PLENIUM Cobranças", custoVariavel: true, unidadeCusto: "transacao" },
  pagamentos: { id: "pagamentos", nome: "PLENIUM Pagamentos", custoVariavel: true, unidadeCusto: "transacao" },
  carteira: { id: "carteira", nome: "PLENIUM Carteira", custoVariavel: false },
  fidelidade: { id: "fidelidade", nome: "PLENIUM Fidelidade", custoVariavel: false },
  pacotes: { id: "pacotes", nome: "PLENIUM Pacotes", custoVariavel: false },
  monitor: { id: "monitor", nome: "PLENIUM Monitor", custoVariavel: true, unidadeCusto: "consulta/processo monitorado" },
  mail: { id: "mail", nome: "PLENIUM Mail", custoVariavel: true, unidadeCusto: "conta/armazenamento" },
  forms: { id: "forms", nome: "PLENIUM Forms", custoVariavel: false },
  atendimento: { id: "atendimento", nome: "PLENIUM Atendimento", custoVariavel: false },
});
