
export const portfolioThemes = {
  educacao: {
    name: "NEXUS Educação",
    label: "Educação",
    accent: "#2563eb",
    accentStrong: "#1d4ed8",
    soft: "#eaf2ff",
    surface: "#ffffff",
    text: "#111827",
    description: "Gestão educacional integrada para instituições, unidades, professores, alunos e famílias.",
  },
  saude: {
    name: "NEXUS Saúde",
    label: "Saúde",
    accent: "#0f9f6e",
    accentStrong: "#087f5b",
    soft: "#e7f8f1",
    surface: "#ffffff",
    text: "#10231d",
    description: "Experiência clínica clara, segura e orientada ao cuidado.",
  },
  restaurantes: {
    name: "NEXUS Restaurantes",
    label: "Restaurantes",
    accent: "#f59e0b",
    accentStrong: "#d97706",
    soft: "#2a2118",
    surface: "#171717",
    text: "#f9fafb",
    description: "Operação dinâmica para atendimento, cozinha, estoque e delivery.",
  },
  governamental: {
    name: "NEXUS Governamental",
    label: "Governamental",
    accent: "#0b5cab",
    accentStrong: "#084b8a",
    soft: "#e9f1f8",
    surface: "#ffffff",
    text: "#172033",
    description: "Produtividade institucional, processos, indicadores e rastreabilidade.",
  },
};
