"use client";
import { useEffect, useMemo, useState } from "react";
const STATUS=[["draft","Rascunho"],["active","Ativo"],["suspended","Suspenso"],["ended","Encerrado"],["cancelled","Cancelado"]];
const INITIAL={clientId:"",number:"",startDate:"",endDate:"",billingCycle:"monthly",value:"",status:"draft",notes:""};
const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0));
export default function ContractsSection(){
 const [contracts,setContracts]=useState([]),[clients,setClients]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[open,setOpen]=useState(false),[message,setMessage]=useState(""),[form,setForm]=useState(INITIAL);
 async function load(){setLoading(true);try{const [a,b]=await Promise.all([fetch("/api/admin/contratos",{cache:"no-store"}),fetch("/api/admin/clientes",{cache:"no-store"})]);const x=await a.json(),y=await b.json();if(!a.ok)throw new Error(x.message);if(!b.ok)throw new Error(y.message);setContracts(x.contracts||[]);setClients(y.clients||[])}catch(e){setMessage(e.message||"Falha ao carregar contratos.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const s=useMemo(()=>({total:contracts.length,active:contracts.filter(x=>x.status==="active").length,mrr:contracts.filter(x=>x.status==="active"&&x.billing_cycle==="monthly").reduce((n,x)=>n+Number(x.value||0),0),ending:contracts.filter(x=>x.end_date&&x.status==="active"&&(new Date(x.end_date)-new Date())/86400000>=0&&(new Date(x.end_date)-new Date())/86400000<=30).length}),[contracts]);
 async function save(e){e.preventDefault();setSaving(true);try{const r=await fetch("/api/admin/contratos",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)throw new Error(d.message);setOpen(false);setForm(INITIAL);await load();setMessage("Contrato cadastrado com sucesso.")}catch(e){setMessage(e.message||"Falha ao cadastrar contrato.")}finally{setSaving(false)}}
 return <><section className="root2-section-intro root2-clients-intro"><div><span>GESTÃO COMERCIAL</span><h2>Contratos</h2><p>Centralize vigência, faturamento e situação contratual dos clientes.</p></div><button className="root2-button primary" onClick={()=>setOpen(true)}>+ Novo contrato</button></section>
 <section className="root2-client-summary"><article><span>Contratos</span><strong>{loading?"…":s.total}</strong><small>Total cadastrado</small></article><article><span>Ativos</span><strong>{loading?"…":s.active}</strong><small>Operação vigente</small></article><article><span>MRR contratual</span><strong>{loading?"…":money(s.mrr)}</strong><small>Mensais ativos</small></article><article><span>Vencem em 30 dias</span><strong>{loading?"…":s.ending}</strong><small>Atenção para renovação</small></article></section>
 {message&&<div className="root2-client-message info">{message}</div>}<section className="root2-panel root2-client-management"><header className="root2-panel-header"><div><span>CARTEIRA CONTRATUAL</span><h3>Contratos cadastrados</h3></div></header><div className="nexus-contract-table-wrap"><table className="nexus-contract-table"><thead><tr><th>Contrato</th><th>Cliente</th><th>Vigência</th><th>Ciclo</th><th>Valor</th><th>Status</th></tr></thead><tbody>{!loading&&!contracts.length?<tr><td colSpan="6">Nenhum contrato cadastrado.</td></tr>:contracts.map(x=><tr key={x.id}><td>{x.number}</td><td>{x.client_name||"—"}</td><td>{x.start_date||"—"} → {x.end_date||"indeterminado"}</td><td>{x.billing_cycle==="annual"?"Anual":"Mensal"}</td><td>{money(x.value)}</td><td>{STATUS.find(s=>s[0]===x.status)?.[1]||x.status}</td></tr>)}</tbody></table></div></section>
 {open&&<div className="root2-modal-backdrop"><section className="root2-modal nexus-contract-modal"><header><div><span>NOVO CONTRATO</span><h3>Dados contratuais</h3></div></header><form onSubmit={save}><div className="nexus-contract-form"><label className="span-2"><span>Cliente *</span><select required value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}><option value="">Selecione</option>{clients.map(c=><option key={c.id} value={c.id}>{c.trade_name||c.legal_name||c.name}</option>)}</select></label><label><span>Número *</span><input required value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></label><label><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{STATUS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label><span>Início *</span><input required type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label><span>Término</span><input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label><label><span>Ciclo</span><select value={form.billingCycle} onChange={e=>setForm({...form,billingCycle:e.target.value})}><option value="monthly">Mensal</option><option value="annual">Anual</option></select></label><label><span>Valor (R$) *</span><input required type="number" min="0" step=".01" value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/></label><label className="span-2"><span>Observações</span><textarea rows="4" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><footer><button type="button" className="root2-button neutral" onClick={()=>setOpen(false)}>Cancelar</button><button className="root2-button primary" disabled={saving}>{saving?"Salvando…":"Cadastrar contrato"}</button></footer></form></section></div>}</>}
