"use client";

import { useEffect, useMemo, useState } from "react";
import "./products.css";

const TYPES = ["PRODUTO", "PLANO", "MODULO", "ADICIONAL", "FACILITY"];
const SEGMENTS = ["Todos", "Governamental", "Educação", "Saúde", "Hotelaria", "Restaurantes", "Jurídico", "Imobiliário"];
const INITIAL = { code:"", name:"", productType:"PRODUTO", segment:"Todos", description:"", monthlyPrice:"", annualPrice:"", implementationFee:"", standalone:true, comboEligible:true, active:true };

function money(value){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value||0));}
function labelType(type){return ({PRODUTO:"Produto",PLANO:"Plano",MODULO:"Módulo",ADICIONAL:"Adicional",FACILITY:"Facility"})[type]||type;}

export default function ProductsSection(){
 const [products,setProducts]=useState([]),[form,setForm]=useState(INITIAL),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 async function load(){try{const r=await fetch("/api/admin/produtos",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message);setProducts(d.products||[]);}catch(e){setMessage(e.message||"Não foi possível carregar o catálogo.");}}
 useEffect(()=>{load();},[]);
 const summary=useMemo(()=>({total:products.length,active:products.filter(x=>x.active).length,standalone:products.filter(x=>x.standalone).length,combo:products.filter(x=>x.combo_eligible).length}),[products]);
 async function save(e){e.preventDefault();setSaving(true);setMessage("");try{const r=await fetch("/api/admin/produtos",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.message);setOpen(false);setForm(INITIAL);await load();setMessage("Item incluído no catálogo comercial.");}catch(err){setMessage(err.message||"Falha ao cadastrar item.");}finally{setSaving(false);}}
 return <>
  <section className="root2-section-intro root2-clients-intro"><div><span>CATÁLOGO COMERCIAL</span><h2>Planos e módulos</h2><p>Organize Produtos, Planos, Módulos, Adicionais e Facilities que poderão compor os contratos.</p></div><button className="root2-button primary" onClick={()=>setOpen(true)}>+ Novo item</button></section>
  <section className="root2-client-summary"><article><span>Itens</span><strong>{summary.total}</strong><small>Total no catálogo</small></article><article><span>Ativos</span><strong>{summary.active}</strong><small>Disponíveis</small></article><article><span>Venda individual</span><strong>{summary.standalone}</strong><small>Contratáveis isoladamente</small></article><article><span>Elegíveis a combo</span><strong>{summary.combo}</strong><small>Geram benefício multiproduto</small></article></section>
  {message&&<div className="root2-client-message info">{message}</div>}
  <section className="root2-panel root2-client-management"><header className="root2-panel-header"><div><span>PORTFÓLIO PLENIUM</span><h3>Catálogo comercial</h3></div></header><div className="nexus-products-grid">{!products.length?<p>Nenhum item cadastrado.</p>:products.map(p=><article key={p.id} className="nexus-product-card"><div className="nexus-product-card-top"><span>{p.code}</span><b>{p.active?"Ativo":"Inativo"}</b></div><div className="nexus-product-tags"><i>{labelType(p.product_type)}</i><i>{p.segment}</i>{p.standalone&&<i>Venda individual</i>}{p.combo_eligible&&<i>Combo</i>}</div><h3>{p.name}</h3>{p.description&&<p className="nexus-product-description">{p.description}</p>}<div className="nexus-product-card-prices"><div><small>Mensal</small><strong>{money(p.monthly_price)}</strong></div><div><small>Anual</small><strong>{money(p.annual_price||Number(p.monthly_price||0)*12)}</strong></div></div>{Number(p.implementation_fee||0)>0&&<div className="nexus-implementation">Implantação: <strong>{money(p.implementation_fee)}</strong></div>}</article>)}</div></section>
  {open&&<div className="root2-modal-backdrop"><section className="root2-modal nexus-product-modal"><header><div><span>NOVO ITEM</span><h3>Catálogo comercial</h3></div></header><form onSubmit={save}><div className="nexus-product-form"><label><span>Código *</span><input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})} placeholder="WEBSITE"/></label><label><span>Nome *</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="PLENIUM Website"/></label><label><span>Tipo *</span><select value={form.productType} onChange={e=>setForm({...form,productType:e.target.value})}>{TYPES.map(x=><option key={x} value={x}>{labelType(x)}</option>)}</select></label><label><span>Segmento</span><select value={form.segment} onChange={e=>setForm({...form,segment:e.target.value})}>{SEGMENTS.map(x=><option key={x}>{x}</option>)}</select></label><label className="nexus-product-wide"><span>Descrição / escopo</span><textarea rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Principais recursos e finalidade comercial"/></label><label><span>Preço mensal (R$) *</span><input required type="number" min="0" step="0.01" value={form.monthlyPrice} onChange={e=>setForm({...form,monthlyPrice:e.target.value})}/></label><label><span>Preço anual (R$)</span><input type="number" min="0" step="0.01" value={form.annualPrice} onChange={e=>setForm({...form,annualPrice:e.target.value})} placeholder="Se vazio: mensal × 12"/></label><label><span>Implantação (R$)</span><input type="number" min="0" step="0.01" value={form.implementationFee} onChange={e=>setForm({...form,implementationFee:e.target.value})}/></label><div className="nexus-product-options"><label><input type="checkbox" checked={form.standalone} onChange={e=>setForm({...form,standalone:e.target.checked})}/><span>Pode ser contratado individualmente</span></label><label><input type="checkbox" checked={form.comboEligible} onChange={e=>setForm({...form,comboEligible:e.target.checked})}/><span>Elegível para desconto por combo</span></label></div></div><footer><button type="button" className="root2-button neutral" onClick={()=>setOpen(false)}>Cancelar</button><button className="root2-button primary" disabled={saving}>{saving?"Salvando…":"Cadastrar item"}</button></footer></form></section></div>}
 </>;
}
